#!/usr/bin/env Rscript

# ==============================================================================
# run_deseq2_contrast.R
# ==============================================================================
# Reusable DESeq2 binary-contrast runner for ROSMAP.
#
# It starts from the globally filtered raw-count matrix generated by
# prepare_rosmap_master_expression.R so every DESeq2 comparison can use the same
# master gene universe as AREA.
#
# Two grouping modes are supported:
#   1) values    : compare two exact metadata values (e.g., diagnosis 4 vs 1)
#   2) threshold : define case/control by numeric ranges (e.g., age >=85 vs <=75)
#
# Complete-case filtering for covariates happens ONLY within the requested
# contrast, so the master 636-sample project dataset is never globally reduced.
# ==============================================================================

usage <- function() {
  cat(paste0(
    "Usage (exact values):\n",
    "  Rscript run_deseq2_contrast.R \\\n",
    "    --counts results/preprocessing/ROSMAP_raw_counts_global_gene_universe.rds \\\n",
    "    --metadata results/preprocessing/ROSMAP_RNAseq_master_metadata_all_samples.csv \\\n",
    "    --outdir results/deseq2/AD_vs_NCI \\\n",
    "    --label AD_vs_NCI \\\n",
    "    --mode values \\\n",
    "    --group-column diagnosis \\\n",
    "    --case-value 4 \\\n",
    "    --control-value 1 \\\n",
    "    --case-label AD \\\n",
    "    --control-label NCI \\\n",
    "    --covariates sex,age_numeric,rin_numeric,pmi_numeric \\\n",
    "    --factor-covariates sex \\\n",
    "    --independent-filtering false\n\n",
    "Usage (numeric threshold/ranges):\n",
    "  Rscript run_deseq2_contrast.R \\\n",
    "    --counts ... \\\n",
    "    --metadata ... \\\n",
    "    --outdir results/deseq2/older_vs_younger \\\n",
    "    --label older_vs_younger \\\n",
    "    --mode threshold \\\n",
    "    --group-column age_numeric \\\n",
    "    --case-min 85 \\\n",
    "    --control-max 75 \\\n",
    "    --case-label Older \\\n",
    "    --control-label Younger \\\n",
    "    --covariates sex,rin_numeric,pmi_numeric \\\n",
    "    --factor-covariates sex\n\n",
    "Required for all modes:\n",
    "  --counts, --metadata, --outdir, --label, --mode, --group-column\n\n",
    "Mode=values also requires:\n",
    "  --case-value, --control-value\n\n",
    "Mode=threshold requires at least one bound for case and control:\n",
    "  --case-min / --case-max / --control-min / --control-max\n\n",
    "Optional:\n",
    "  --case-label              Default: case value or 'Case'\n",
    "  --control-label           Default: control value or 'Control'\n",
    "  --covariates              Comma-separated; default: none\n",
    "  --factor-covariates       Comma-separated covariates to treat as factors\n",
    "  --independent-filtering   true/false; default: false\n",
    "  --alpha                   Adjusted-p significance threshold; default: 0.05\n",
    "  --lfc-threshold           Optional reporting threshold; default: 0.5\n",
    "  --help                    Show this message\n"
  ))
}

parse_args <- function(args) {
  if (length(args) == 0 || any(args %in% c("--help", "-h"))) {
    usage()
    quit(status = ifelse(length(args) == 0, 1, 0))
  }
  out <- list()
  i <- 1
  while (i <= length(args)) {
    key <- args[[i]]
    if (!startsWith(key, "--")) stop("Unexpected argument: ", key)
    if (i == length(args)) stop("Missing value for argument: ", key)
    out[[substring(key, 3)]] <- args[[i + 1]]
    i <- i + 2
  }
  out
}

split_csv_arg <- function(x) {
  if (is.null(x) || !nzchar(trimws(x))) return(character(0))
  trimws(strsplit(x, ",", fixed = TRUE)[[1]])
}

as_bool <- function(x, name) {
  val <- tolower(trimws(x))
  if (val %in% c("true", "t", "1", "yes", "y")) return(TRUE)
  if (val %in% c("false", "f", "0", "no", "n")) return(FALSE)
  stop(name, " must be true or false.")
}

num_or_null <- function(x, name) {
  if (is.null(x)) return(NULL)
  y <- suppressWarnings(as.numeric(x))
  if (!is.finite(y)) stop(name, " must be numeric.")
  y
}

args <- parse_args(commandArgs(trailingOnly = TRUE))

required <- c("counts", "metadata", "outdir", "label", "mode", "group-column")
missing_required <- required[!required %in% names(args)]
if (length(missing_required) > 0) {
  stop("Missing required argument(s): ", paste(paste0("--", missing_required), collapse = ", "))
}

count_file <- path.expand(args$counts)
metadata_file <- path.expand(args$metadata)
outdir <- args$outdir
label <- args$label
mode <- tolower(args$mode)
group_column <- args[["group-column"]]
covariates <- split_csv_arg(args$covariates)
factor_covariates <- split_csv_arg(args[["factor-covariates"]])
independent_filtering <- if (!is.null(args[["independent-filtering"]])) {
  as_bool(args[["independent-filtering"]], "--independent-filtering")
} else FALSE
alpha <- if (!is.null(args$alpha)) as.numeric(args$alpha) else 0.05
lfc_threshold <- if (!is.null(args[["lfc-threshold"]])) as.numeric(args[["lfc-threshold"]]) else 0.5

if (!mode %in% c("values", "threshold")) stop("--mode must be 'values' or 'threshold'.")
if (!file.exists(count_file)) stop("Count file not found: ", count_file)
if (!file.exists(metadata_file)) stop("Metadata file not found: ", metadata_file)
if (!is.finite(alpha) || alpha <= 0 || alpha >= 1) stop("--alpha must be between 0 and 1.")
if (!is.finite(lfc_threshold) || lfc_threshold < 0) stop("--lfc-threshold must be >= 0.")

dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

required_packages <- c("DESeq2")
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_packages) > 0) {
  stop("Missing required package(s): ", paste(missing_packages, collapse = ", "))
}
suppressPackageStartupMessages(library(DESeq2))

# ------------------------------------------------------------------------------
# 1. Load global-universe counts and master metadata
# ------------------------------------------------------------------------------
counts <- readRDS(count_file)
if (!is.matrix(counts)) stop("--counts must be an RDS matrix.")
if (anyNA(counts) || any(counts < 0) || !all(counts == floor(counts))) {
  stop("Count matrix failed raw-count validation.")
}

meta <- read.csv(metadata_file, stringsAsFactors = FALSE, check.names = FALSE)
if (!"sample_id" %in% colnames(meta)) stop("Metadata must contain sample_id.")
if (!group_column %in% colnames(meta)) stop("Metadata does not contain group column: ", group_column)

# Re-create common numeric convenience fields if someone supplies the original
# merged metadata instead of the master metadata output.
if (!"age_numeric" %in% colnames(meta) && "age" %in% colnames(meta)) {
  age_chr <- trimws(as.character(meta$age))
  meta$age_numeric <- ifelse(age_chr == "90+", 90, suppressWarnings(as.numeric(age_chr)))
}
if (!"rin_numeric" %in% colnames(meta) && "rin" %in% colnames(meta)) {
  meta$rin_numeric <- suppressWarnings(as.numeric(meta$rin))
}
if (!"pmi_numeric" %in% colnames(meta) && "pmi" %in% colnames(meta)) {
  meta$pmi_numeric <- suppressWarnings(as.numeric(meta$pmi))
}

missing_covariates <- setdiff(covariates, colnames(meta))
if (length(missing_covariates) > 0) {
  stop("Metadata is missing requested covariate(s): ", paste(missing_covariates, collapse = ", "))
}
if (group_column %in% covariates) {
  stop(
    "The grouping column ('", group_column, "') is also listed as a covariate. ",
    "Remove it from --covariates to avoid modeling the same variable twice."
  )
}
if (any(!factor_covariates %in% covariates)) {
  stop("Every --factor-covariates entry must also appear in --covariates.")
}
if (anyDuplicated(meta$sample_id)) stop("Metadata contains duplicate sample_id values.")

common_samples <- intersect(colnames(counts), meta$sample_id)
if (length(common_samples) == 0) stop("No count-matrix sample IDs matched metadata.")

# Preserve count-matrix order.
common_samples <- colnames(counts)[colnames(counts) %in% common_samples]
meta_aligned <- meta[match(common_samples, meta$sample_id), , drop = FALSE]
counts_aligned <- counts[, common_samples, drop = FALSE]
stopifnot(identical(colnames(counts_aligned), meta_aligned$sample_id))

# ------------------------------------------------------------------------------
# 2. Define case/control samples
# ------------------------------------------------------------------------------
if (mode == "values") {
  if (is.null(args[["case-value"]]) || is.null(args[["control-value"]])) {
    stop("mode=values requires --case-value and --control-value.")
  }
  case_value <- args[["case-value"]]
  control_value <- args[["control-value"]]
  group_chr <- trimws(as.character(meta_aligned[[group_column]]))
  case_mask <- !is.na(group_chr) & group_chr == case_value
  control_mask <- !is.na(group_chr) & group_chr == control_value
  case_label <- if (!is.null(args[["case-label"]])) args[["case-label"]] else case_value
  control_label <- if (!is.null(args[["control-label"]])) args[["control-label"]] else control_value
} else {
  x <- suppressWarnings(as.numeric(meta_aligned[[group_column]]))
  case_min <- num_or_null(args[["case-min"]], "--case-min")
  case_max <- num_or_null(args[["case-max"]], "--case-max")
  control_min <- num_or_null(args[["control-min"]], "--control-min")
  control_max <- num_or_null(args[["control-max"]], "--control-max")

  if (is.null(case_min) && is.null(case_max)) stop("Threshold mode needs --case-min and/or --case-max.")
  if (is.null(control_min) && is.null(control_max)) stop("Threshold mode needs --control-min and/or --control-max.")

  within_bounds <- function(v, lo, hi) {
    keep <- !is.na(v)
    if (!is.null(lo)) keep <- keep & v >= lo
    if (!is.null(hi)) keep <- keep & v <= hi
    keep
  }

  case_mask <- within_bounds(x, case_min, case_max)
  control_mask <- within_bounds(x, control_min, control_max)

  if (any(case_mask & control_mask)) {
    stop("Case and control numeric ranges overlap. Choose non-overlapping bounds.")
  }

  case_label <- if (!is.null(args[["case-label"]])) args[["case-label"]] else "Case"
  control_label <- if (!is.null(args[["control-label"]])) args[["control-label"]] else "Control"
}

selected <- case_mask | control_mask
if (sum(case_mask) == 0) stop("No case samples matched the requested definition.")
if (sum(control_mask) == 0) stop("No control samples matched the requested definition.")

meta_sub <- meta_aligned[selected, , drop = FALSE]
counts_sub <- counts_aligned[, selected, drop = FALSE]
meta_sub$analysis_group <- ifelse(case_mask[selected], case_label, control_label)

cat("\n============================================================\n")
cat("DESeq2 CONTRAST: ", label, "\n", sep = "")
cat("============================================================\n")
cat("Master gene universe: ", nrow(counts), " genes\n", sep = "")
cat("Samples before phenotype selection: ", ncol(counts_aligned), "\n", sep = "")
cat("Selected case samples:    ", sum(meta_sub$analysis_group == case_label), " (", case_label, ")\n", sep = "")
cat("Selected control samples: ", sum(meta_sub$analysis_group == control_label), " (", control_label, ")\n", sep = "")

# ------------------------------------------------------------------------------
# 3. Contrast-specific complete-case filtering
# ------------------------------------------------------------------------------
complete_columns <- c("analysis_group", covariates)
complete_mask <- complete.cases(meta_sub[, complete_columns, drop = FALSE])

excluded_missing <- meta_sub[!complete_mask, c("sample_id", complete_columns), drop = FALSE]
if (nrow(excluded_missing) > 0) {
  write.csv(
    excluded_missing,
    file.path(outdir, paste0(label, "_samples_excluded_missing_covariates.csv")),
    row.names = FALSE
  )
}

meta_model <- meta_sub[complete_mask, , drop = FALSE]
counts_model <- counts_sub[, complete_mask, drop = FALSE]

if (sum(meta_model$analysis_group == case_label) < 2 || sum(meta_model$analysis_group == control_label) < 2) {
  stop("Fewer than 2 samples remain in at least one group after complete-case filtering.")
}

meta_model$analysis_group <- factor(meta_model$analysis_group, levels = c(control_label, case_label))

# Explicitly factor user-specified categorical covariates. Numeric covariates are
# centered (not scaled) for model stability and easier interpretation.
model_covariates <- character(0)
for (covar in covariates) {
  if (covar %in% factor_covariates) {
    meta_model[[covar]] <- factor(meta_model[[covar]])
    if (nlevels(meta_model[[covar]]) < 2) {
      stop("Factor covariate '", covar, "' has fewer than 2 levels in this contrast.")
    }
    model_covariates <- c(model_covariates, covar)
  } else {
    numeric_value <- suppressWarnings(as.numeric(meta_model[[covar]]))
    if (anyNA(numeric_value)) {
      stop(
        "Covariate '", covar, "' is not fully numeric. ",
        "If it is categorical, include it in --factor-covariates."
      )
    }
    centered_name <- paste0(covar, "_c")
    meta_model[[centered_name]] <- numeric_value - mean(numeric_value)
    if (sd(meta_model[[centered_name]]) == 0) {
      stop("Numeric covariate '", covar, "' has zero variance in this contrast.")
    }
    model_covariates <- c(model_covariates, centered_name)
  }
}

# analysis_group is always placed last so the intended contrast is explicit.
design_terms <- c(model_covariates, "analysis_group")
design_formula <- as.formula(paste("~", paste(design_terms, collapse = " + ")))

# Basic full-rank design check before running DESeq2.
model_matrix <- model.matrix(design_formula, data = meta_model)
if (qr(model_matrix)$rank < ncol(model_matrix)) {
  stop(
    "The requested model matrix is not full rank. This usually means a covariate ",
    "is redundant/confounded with the case-control grouping."
  )
}

cat("Samples after complete-case filtering: ", nrow(meta_model), "\n", sep = "")
cat("  ", control_label, ": ", sum(meta_model$analysis_group == control_label), "\n", sep = "")
cat("  ", case_label, ": ", sum(meta_model$analysis_group == case_label), "\n", sep = "")
cat("Design: ", deparse(design_formula), "\n", sep = "")
cat("Independent filtering in results(): ", independent_filtering, "\n", sep = "")

# ------------------------------------------------------------------------------
# 4. Run DESeq2 on raw counts for the SAME master gene universe
# ------------------------------------------------------------------------------
rownames(meta_model) <- meta_model$sample_id
stopifnot(identical(colnames(counts_model), rownames(meta_model)))

dds <- DESeqDataSetFromMatrix(
  countData = counts_model,
  colData = meta_model,
  design = design_formula
)

dds <- DESeq(dds)

res <- results(
  dds,
  contrast = c("analysis_group", case_label, control_label),
  alpha = alpha,
  independentFiltering = independent_filtering
)

res_df <- as.data.frame(res)
res_df$ensembl_id_version <- rownames(res_df)
res_df$ensembl_id <- sub("\\..*$", "", res_df$ensembl_id_version)

# Optional symbol annotation; analysis remains Ensembl-ID based.
res_df$gene_symbol <- NA_character_
if (requireNamespace("AnnotationDbi", quietly = TRUE) && requireNamespace("org.Hs.eg.db", quietly = TRUE)) {
  suppressPackageStartupMessages({
    library(AnnotationDbi)
    library(org.Hs.eg.db)
  })
  res_df$gene_symbol <- AnnotationDbi::mapIds(
    org.Hs.eg.db,
    keys = res_df$ensembl_id,
    column = "SYMBOL",
    keytype = "ENSEMBL",
    multiVals = "first"
  )
}

res_df <- res_df[order(res_df$padj, res_df$pvalue, na.last = TRUE), ]

sig_fdr <- !is.na(res_df$padj) & res_df$padj < alpha
sig_fdr_lfc <- sig_fdr & !is.na(res_df$log2FoldChange) & abs(res_df$log2FoldChange) >= lfc_threshold

# ------------------------------------------------------------------------------
# 5. Export results and provenance
# ------------------------------------------------------------------------------
write.csv(res_df, file.path(outdir, paste0(label, "_DESeq2_all_results.csv")), row.names = FALSE)
write.csv(res_df[sig_fdr, , drop = FALSE], file.path(outdir, paste0(label, "_DESeq2_FDR", alpha, "_significant.csv")), row.names = FALSE)
write.csv(
  res_df[sig_fdr_lfc, , drop = FALSE],
  file.path(outdir, paste0(label, "_DESeq2_FDR", alpha, "_LFC", lfc_threshold, "_significant.csv")),
  row.names = FALSE
)
write.csv(meta_model, file.path(outdir, paste0(label, "_sample_manifest.csv")), row.names = FALSE)
saveRDS(dds, file.path(outdir, paste0(label, "_dds.rds")))

summary_df <- data.frame(
  metric = c(
    "master_genes_tested",
    "samples_modeled",
    paste0("n_", control_label),
    paste0("n_", case_label),
    "alpha",
    "independent_filtering",
    "padj_significant_genes",
    paste0("padj_significant_absLFC_ge_", lfc_threshold)
  ),
  value = c(
    nrow(res_df),
    nrow(meta_model),
    sum(meta_model$analysis_group == control_label),
    sum(meta_model$analysis_group == case_label),
    alpha,
    independent_filtering,
    sum(sig_fdr),
    sum(sig_fdr_lfc)
  ),
  stringsAsFactors = FALSE
)
write.csv(summary_df, file.path(outdir, paste0(label, "_DESeq2_summary.csv")), row.names = FALSE)

sink(file.path(outdir, paste0(label, "_DESeq2_sessionInfo.txt")))
cat("Label: ", label, "\n", sep = "")
cat("Group column: ", group_column, "\n", sep = "")
cat("Mode: ", mode, "\n", sep = "")
cat("Contrast: ", case_label, " vs ", control_label, "\n", sep = "")
cat("Design: ", deparse(design_formula), "\n", sep = "")
cat("Independent filtering: ", independent_filtering, "\n\n", sep = "")
print(summary_df)
cat("\n")
print(sessionInfo())
sink()

cat("\n============================================================\n")
cat("DESeq2 COMPLETE: ", label, "\n", sep = "")
cat("============================================================\n")
print(summary_df, row.names = FALSE)
cat("\nResults written to: ", outdir, "\n", sep = "")
