#!/usr/bin/env python3
"""
refine_weighted_area_biology_modules.py
=======================================

Turn the broad Weighted AREA pathway synthesis into a smaller, biologically
interpretable module-level analysis.

This script DOES NOT rerun GSEA. It consumes the outputs already generated by:

    exploratory/enrichment/analyze_weighted_area_biology.py

and collapses hundreds of overlapping pathways into a transparent set of
biological modules.

Main questions
--------------
1. What are the dominant biological modules?
2. Which modules form a shared core across cognition, amyloid, and tau?
3. Which modules are relatively enhanced for amyloid, tau, or cognition?
4. Which genes repeatedly drive each module without simply being global
   annotation hubs?
5. Which representative pathways support each module?

Method
------
Pathways are first reduced to the previously selected representative pathways
(from leading-edge Jaccard redundancy clustering). Representative pathways are
then assigned to biologically interpretable modules by explicit keyword rules.

The rules are intentionally transparent and are exported to CSV so that every
module assignment can be audited.

For each module and phenotype:
    module NES = median NES across assigned representative pathways

For each module and phenotype:
    significant fraction = fraction of assigned representative pathways with
                           GSEA FDR < 0.05

A module is called:
    Shared core
        if it has >= 1 significant representative pathway in all 3 axes and
        its mean NES has the same sign in all 3 axes.

    <axis>-enhanced
        if it is shared across all 3 axes, but one axis has an absolute mean
        NES at least ENHANCEMENT_DELTA larger than the mean of the other axes.

    <axis>-specific
        only under a stricter criterion: >= MIN_AXIS_SIG representative
        pathways significant on one axis, zero significant representatives on
        the other two axes, and weak mean signal on both other axes.

    Mixed / context-dependent
        otherwise.

Leading-edge genes
------------------
Global hub genes can dominate recurrence counts. Therefore module driver genes
are ranked by BOTH:
    - recurrence within the module
    - module specificity = module recurrence / recurrence across all modules

This makes the gene tables more useful than the earlier global UBC/proteasome
recurrence ranking.

Inputs
------
results/weighted_area_biology/
    pathway_long_all.csv
    representative_pathways.csv
    redundancy_clusters.csv

Outputs
-------
results/weighted_area_biology_refined/

Tables:
    module_assignment_audit.csv
    module_summary.csv
    module_phenotype_profiles.csv
    module_axis_profiles.csv
    module_driver_genes.csv
    module_representative_pathways.csv
    unassigned_representative_pathways.csv
    module_rules.csv

Figures:
    refined_module_phenotype_heatmap.png/.pdf
    refined_module_axis_profiles.png/.pdf
    refined_module_driver_genes.png/.pdf
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path
import argparse
import re

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# =============================================================================
# CONFIGURATION
# =============================================================================

PHENOTYPES = [
    "Cognitive_stage",
    "cogn_global_impairment",
    "mmse_impairment",
    "CERAD_equal",
    "CERAD_amyloid_calibrated",
    "amyloid_continuous",
    "Braak_equal",
    "Braak_tangle_calibrated",
    "tangle_continuous",
]

PHENOTYPE_LABELS = {
    "Cognitive_stage": "Cognitive\nstage",
    "cogn_global_impairment": "Global\ncognition",
    "mmse_impairment": "MMSE",
    "CERAD_equal": "CERAD\nequal",
    "CERAD_amyloid_calibrated": "CERAD\ncalibrated",
    "amyloid_continuous": "Amyloid\ncontinuous",
    "Braak_equal": "Braak\nequal",
    "Braak_tangle_calibrated": "Braak\ncalibrated",
    "tangle_continuous": "Tangles\ncontinuous",
}

AXIS_MAP = {
    "Cognitive_stage": "Cognition",
    "cogn_global_impairment": "Cognition",
    "mmse_impairment": "Cognition",
    "CERAD_equal": "Amyloid",
    "CERAD_amyloid_calibrated": "Amyloid",
    "amyloid_continuous": "Amyloid",
    "Braak_equal": "Tau",
    "Braak_tangle_calibrated": "Tau",
    "tangle_continuous": "Tau",
}

AXES = ["Cognition", "Amyloid", "Tau"]

# Enhancement threshold in absolute mean NES.
ENHANCEMENT_DELTA = 0.25

# Strict axis-specific requirements.
MIN_AXIS_SIG = 2
OTHER_AXIS_WEAK_ABS_NES = 1.30

# For heatmap dot: at least this fraction of representative pathways in a module
# must be significant for that phenotype.
MODULE_SIG_FRACTION_FOR_DOT = 0.50

# Driver-gene filtering.
MIN_DRIVER_RECURRENCE = 2
MIN_DRIVER_SPECIFICITY = 0.35

TEXT = "#171717"
MUTED = "#5A5A5A"

plt.rcParams.update(
    {
        "font.family": "DejaVu Sans",
        "axes.titlesize": 7.2,
        "axes.titleweight": "bold",
        "axes.labelsize": 6.1,
        "xtick.labelsize": 5.4,
        "ytick.labelsize": 5.4,
        "legend.fontsize": 5.3,
    }
)


# =============================================================================
# BIOLOGICAL MODULE RULES
# =============================================================================

# Rules are ordered. A representative pathway is assigned to the FIRST matching
# module. Keep more specific modules above broader ones.
MODULE_RULES = [
    {
        "module": "Mitochondrial energetics",
        "include": [
            r"oxidative phosphorylation",
            r"respiratory electron transport",
            r"aerobic respiration",
            r"electron transport chain",
            r"proton motive force",
            r"atp synth",
            r"chemiosmotic",
            r"complex i biogenesis",
            r"complex iii assembly",
            r"complex iv",
            r"cytochrome c oxidase",
            r"citric acid cycle",
            r"tricarboxylic acid cycle",
            r"tca cycle",
        ],
        "exclude": [
            r"mitophagy",
            r"protein import",
            r"protein degradation",
        ],
    },
    {
        "module": "Mitochondrial quality control",
        "include": [
            r"mitophagy",
            r"mitochondrial protein import",
            r"mitochondrial protein degradation",
            r"cristae formation",
            r"mitochondrial organization",
            r"mitochondrial membrane organization",
            r"mitochondrial dynamics",
            r"pink1",
            r"prkn",
            r"parkin",
        ],
        "exclude": [],
    },
    {
        "module": "Translation / tRNA biology",
        "include": [
            r"\btranslation\b",
            r"aminoacylation",
            r"trna",
            r"ribosome",
            r"ribosomal",
            r"peptide biosynthetic",
            r"protein targeting to membrane",
            r"cotranslational",
        ],
        "exclude": [
            r"mitochondrial translation",
        ],
    },
    {
        "module": "Protein folding / proteostasis",
        "include": [
            r"prefoldin",
            r"tric",
            r"cct",
            r"protein folding",
            r"chaperon",
            r"proteasom",
            r"ubiquitin",
            r"protein degradation",
            r"protein quality control",
            r"unfolded protein",
        ],
        "exclude": [
            r"mitochondrial protein degradation",
        ],
    },
    {
        "module": "Synaptic transmission",
        "include": [
            r"synap",
            r"neurotransmitter",
            r"glutamate release",
            r"gaba",
            r"acetylcholine",
            r"vesicle exocytosis",
            r"neurexin",
            r"neuroligin",
            r"nmda",
        ],
        "exclude": [],
    },
    {
        "module": "RHO / cytoskeletal signaling",
        "include": [
            r"rho[a-z]* gtpase",
            r"\brhoa\b",
            r"\brhob\b",
            r"\brhoc\b",
            r"cdc42",
            r"rac1",
            r"small gtpase",
            r"actin filament",
            r"cytoskeleton",
            r"microtubule",
            r"tubulin",
        ],
        "exclude": [
            r"vesicle transport along microtubule",
        ],
    },
    {
        "module": "TGF / ECM remodeling",
        "include": [
            r"tgf",
            r"tgfbr",
            r"extracellular matrix",
            r"\becm\b",
            r"integrin",
            r"collagen",
            r"focal adhesion",
            r"matrix organization",
        ],
        "exclude": [],
    },
    {
        "module": "Inflammatory / NF-kB signaling",
        "include": [
            r"nf.?kb",
            r"tumor necrosis factor",
            r"\btnf\b",
            r"interferon",
            r"cytokine",
            r"inflammatory",
            r"immune response",
            r"innate immune",
        ],
        "exclude": [],
    },
    {
        "module": "Stress / hypoxia / metal response",
        "include": [
            r"hypoxia",
            r"response to metal",
            r"metal ion",
            r"oxidative stress",
            r"reactive oxygen",
            r"cellular stress",
            r"heat shock",
        ],
        "exclude": [],
    },
    {
        "module": "Chromatin / transcriptional regulation",
        "include": [
            r"chromatin",
            r"histone",
            r"epigen",
            r"transcription",
            r"e2f",
            r"dream",
            r"hdac",
            r"acetylation",
        ],
        "exclude": [
            r"transcriptional regulation by",
        ],
    },
    {
        "module": "Autophagy / lysosome",
        "include": [
            r"autophagy",
            r"lysosome",
            r"lysosomal",
            r"mitf",
        ],
        "exclude": [
            r"mitophagy",
        ],
    },
    {
        "module": "Cell death / apoptosis",
        "include": [
            r"apopt",
            r"cell death",
            r"p53",
            r"caspase",
        ],
        "exclude": [],
    },
    {
        "module": "WNT / developmental signaling",
        "include": [
            r"\bwnt\b",
            r"beta catenin",
            r"notch",
            r"hedgehog",
            r"developmental",
        ],
        "exclude": [],
    },
    {
        "module": "Vesicle / intracellular transport",
        "include": [
            r"vesicle transport",
            r"protein localization",
            r"intracellular transport",
            r"endocyt",
            r"clathrin",
            r"golgi",
            r"endosomal",
        ],
        "exclude": [
            r"synaptic vesicle",
        ],
    },
]


# =============================================================================
# CLI
# =============================================================================

def parse_args():
    p = argparse.ArgumentParser()

    p.add_argument(
        "--biology-root",
        default="results/weighted_area_biology",
    )

    p.add_argument(
        "--outdir",
        default="results/weighted_area_biology_refined",
    )

    p.add_argument(
        "--top-drivers-per-module",
        type=int,
        default=5,
    )

    p.add_argument(
        "--min-representatives-per-module",
        type=int,
        default=1,
    )

    return p.parse_args()


# =============================================================================
# HELPERS
# =============================================================================

def require(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"Missing required input: {path}")


def normalize_pathway(text: str) -> str:
    text = str(text).replace("_", " ")
    text = re.sub(r"\s+", " ", text).strip()
    return text


def parse_leading_edge(value) -> set[str]:
    if pd.isna(value):
        return set()

    text = str(value).strip()

    if not text:
        return set()

    parts = re.split(r"[;,/|]+", text)

    if len(parts) == 1:
        parts = text.split()

    return {
        p.strip()
        for p in parts
        if p.strip()
        and p.strip().lower() not in {"nan", "none", "na"}
    }


def pathway_matches_rule(pathway: str, rule: dict) -> bool:
    text = normalize_pathway(pathway).lower()

    include_match = any(
        re.search(pattern, text, flags=re.IGNORECASE)
        for pattern in rule["include"]
    )

    if not include_match:
        return False

    exclude_match = any(
        re.search(pattern, text, flags=re.IGNORECASE)
        for pattern in rule["exclude"]
    )

    return not exclude_match


def assign_module(pathway: str) -> tuple[str | None, str | None]:
    for rule in MODULE_RULES:
        if pathway_matches_rule(pathway, rule):
            return rule["module"], "; ".join(rule["include"])

    return None, None


# =============================================================================
# LOAD / ASSIGN REPRESENTATIVE PATHWAYS
# =============================================================================

def load_inputs(root: Path):
    long_path = root / "pathway_long_all.csv"
    rep_path = root / "representative_pathways.csv"
    cluster_path = root / "redundancy_clusters.csv"

    require(long_path)
    require(rep_path)
    require(cluster_path)

    return (
        pd.read_csv(long_path),
        pd.read_csv(rep_path),
        pd.read_csv(cluster_path),
    )


def make_rule_table() -> pd.DataFrame:
    rows = []

    for order, rule in enumerate(MODULE_RULES, start=1):
        rows.append(
            {
                "rule_order": order,
                "module": rule["module"],
                "include_patterns": "; ".join(rule["include"]),
                "exclude_patterns": "; ".join(rule["exclude"]),
            }
        )

    return pd.DataFrame(rows)


def assign_representatives(
    representatives: pd.DataFrame,
) -> pd.DataFrame:

    rows = []

    for _, row in representatives.iterrows():
        module, matched_rule = assign_module(
            row["pathway"]
        )

        out = row.to_dict()
        out["module"] = module
        out["assigned"] = module is not None
        out["matched_rule_patterns"] = matched_rule

        rows.append(out)

    return pd.DataFrame(rows)


# =============================================================================
# MODULE PROFILES
# =============================================================================

def representative_long(
    long_df: pd.DataFrame,
    assignments: pd.DataFrame,
) -> pd.DataFrame:
    assigned = assignments[
        assignments["assigned"]
    ][
        [
            "library",
            "pathway",
            "module",
        ]
    ].drop_duplicates()

    out = long_df.merge(
        assigned,
        on=[
            "library",
            "pathway",
        ],
        how="inner",
    )

    return out


def make_module_phenotype_profiles(
    rep_long: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    for (module, phenotype), sub in rep_long.groupby(
        ["module", "phenotype"]
    ):
        n_reps = sub[
            ["library", "pathway"]
        ].drop_duplicates().shape[0]

        n_sig = sub[
            sub["significant"]
        ][
            ["library", "pathway"]
        ].drop_duplicates().shape[0]

        median_nes = float(
            sub["NES"].median()
        )

        mean_nes = float(
            sub["NES"].mean()
        )

        rows.append(
            {
                "module": module,
                "phenotype": phenotype,
                "phenotype_label": PHENOTYPE_LABELS[phenotype],
                "axis": AXIS_MAP[phenotype],
                "n_representative_pathways": int(n_reps),
                "n_significant_representatives": int(n_sig),
                "significant_fraction": (
                    n_sig / n_reps
                    if n_reps > 0
                    else np.nan
                ),
                "median_NES": median_nes,
                "mean_NES": mean_nes,
                "median_abs_NES": float(
                    sub["NES"].abs().median()
                ),
            }
        )

    return pd.DataFrame(rows)


def make_module_axis_profiles(
    phenotype_profiles: pd.DataFrame,
) -> pd.DataFrame:

    rows = []

    for (module, axis), sub in phenotype_profiles.groupby(
        ["module", "axis"]
    ):
        rows.append(
            {
                "module": module,
                "axis": axis,
                "mean_axis_NES": float(
                    sub["median_NES"].mean()
                ),
                "mean_axis_abs_NES": float(
                    sub["median_NES"].abs().mean()
                ),
                "n_axis_phenotypes": int(
                    sub["phenotype"].nunique()
                ),
                "n_axis_phenotypes_with_module_signal": int(
                    (
                        sub["n_significant_representatives"] > 0
                    ).sum()
                ),
                "mean_significant_fraction": float(
                    sub["significant_fraction"].mean()
                ),
            }
        )

    return pd.DataFrame(rows)


def classify_module(
    module: str,
    axis_profiles: pd.DataFrame,
) -> dict:

    sub = axis_profiles[
        axis_profiles["module"] == module
    ].set_index("axis")

    if not all(
        axis in sub.index
        for axis in AXES
    ):
        return {
            "module_class": "Incomplete",
            "enhanced_axis": "",
            "enhancement_delta": np.nan,
        }

    mean_nes = {
        axis: float(
            sub.loc[
                axis,
                "mean_axis_NES",
            ]
        )
        for axis in AXES
    }

    abs_nes = {
        axis: abs(mean_nes[axis])
        for axis in AXES
    }

    sig_counts = {
        axis: int(
            sub.loc[
                axis,
                "n_axis_phenotypes_with_module_signal",
            ]
        )
        for axis in AXES
    }

    signs = {
        axis: np.sign(mean_nes[axis])
        for axis in AXES
        if mean_nes[axis] != 0
    }

    # Strict axis-specific first.
    for axis in AXES:
        others = [
            x
            for x in AXES
            if x != axis
        ]

        if (
            sig_counts[axis] >= MIN_AXIS_SIG
            and all(
                sig_counts[o] == 0
                for o in others
            )
            and all(
                abs_nes[o] < OTHER_AXIS_WEAK_ABS_NES
                for o in others
            )
        ):
            return {
                "module_class": f"{axis}-specific",
                "enhanced_axis": axis,
                "enhancement_delta": (
                    abs_nes[axis]
                    - np.mean(
                        [
                            abs_nes[o]
                            for o in others
                        ]
                    )
                ),
            }

    all_axes_signal = all(
        sig_counts[axis] >= 1
        for axis in AXES
    )

    same_direction = (
        len(set(signs.values())) == 1
        if len(signs) == 3
        else False
    )

    if all_axes_signal and same_direction:
        best_axis = max(
            AXES,
            key=lambda a: abs_nes[a],
        )

        other_axes = [
            a
            for a in AXES
            if a != best_axis
        ]

        delta = (
            abs_nes[best_axis]
            - np.mean(
                [
                    abs_nes[a]
                    for a in other_axes
                ]
            )
        )

        if delta >= ENHANCEMENT_DELTA:
            return {
                "module_class": f"{best_axis}-enhanced shared",
                "enhanced_axis": best_axis,
                "enhancement_delta": delta,
            }

        return {
            "module_class": "Shared core",
            "enhanced_axis": "",
            "enhancement_delta": delta,
        }

    return {
        "module_class": "Mixed / context-dependent",
        "enhanced_axis": "",
        "enhancement_delta": np.nan,
    }


def make_module_summary(
    assignments: pd.DataFrame,
    phenotype_profiles: pd.DataFrame,
    axis_profiles: pd.DataFrame,
) -> pd.DataFrame:

    rows = []

    assigned = assignments[
        assignments["assigned"]
    ]

    for module, sub in assigned.groupby("module"):

        libraries = sorted(
            sub["library"].unique().tolist()
        )

        rep_count = sub[
            ["library", "pathway"]
        ].drop_duplicates().shape[0]

        class_info = classify_module(
            module,
            axis_profiles,
        )

        axis_lookup = (
            axis_profiles[
                axis_profiles["module"] == module
            ]
            .set_index("axis")
        )

        row = {
            "module": module,
            "n_representative_pathways": int(rep_count),
            "n_libraries": int(len(libraries)),
            "libraries": ";".join(libraries),
            **class_info,
        }

        for axis in AXES:
            if axis in axis_lookup.index:
                row[f"{axis.lower()}_mean_NES"] = float(
                    axis_lookup.loc[
                        axis,
                        "mean_axis_NES",
                    ]
                )
                row[f"{axis.lower()}_mean_abs_NES"] = float(
                    axis_lookup.loc[
                        axis,
                        "mean_axis_abs_NES",
                    ]
                )
                row[f"{axis.lower()}_signal_phenotypes"] = int(
                    axis_lookup.loc[
                        axis,
                        "n_axis_phenotypes_with_module_signal",
                    ]
                )
            else:
                row[f"{axis.lower()}_mean_NES"] = np.nan
                row[f"{axis.lower()}_mean_abs_NES"] = np.nan
                row[f"{axis.lower()}_signal_phenotypes"] = 0

        row["overall_mean_abs_NES"] = float(
            phenotype_profiles[
                phenotype_profiles["module"] == module
            ]["median_NES"]
            .abs()
            .mean()
        )

        rows.append(row)

    return pd.DataFrame(rows).sort_values(
        [
            "n_representative_pathways",
            "overall_mean_abs_NES",
        ],
        ascending=[
            False,
            False,
        ],
    )


# =============================================================================
# MODULE DRIVER GENES
# =============================================================================

def make_driver_genes(
    rep_long: pd.DataFrame,
) -> pd.DataFrame:

    rows = []

    sig = rep_long[
        rep_long["significant"]
    ].copy()

    for _, row in sig.iterrows():
        genes = parse_leading_edge(
            row["leading_edge_genes"]
        )

        for gene in genes:
            rows.append(
                {
                    "module": row["module"],
                    "gene": gene,
                    "library": row["library"],
                    "pathway": row["pathway"],
                    "phenotype": row["phenotype"],
                    "axis": row["axis"],
                    "NES": row["NES"],
                }
            )

    if not rows:
        return pd.DataFrame()

    exploded = pd.DataFrame(rows)

    module_counts = (
        exploded
        .groupby(
            [
                "module",
                "gene",
            ]
        )
        .agg(
            module_pathway_instances=("pathway", "size"),
            module_unique_pathways=("pathway", "nunique"),
            module_phenotypes=("phenotype", "nunique"),
            module_axes=("axis", "nunique"),
            mean_context_NES=("NES", "mean"),
        )
        .reset_index()
    )

    global_counts = (
        exploded
        .groupby("gene")
        .agg(
            global_pathway_instances=("pathway", "size"),
            global_unique_modules=("module", "nunique"),
        )
        .reset_index()
    )

    out = module_counts.merge(
        global_counts,
        on="gene",
        how="left",
    )

    out["module_specificity"] = (
        out["module_pathway_instances"]
        / out["global_pathway_instances"]
    )

    # Recurrence plus specificity. sqrt prevents huge recurrence counts from
    # completely dominating the ranking.
    out["driver_score"] = (
        np.sqrt(
            out["module_pathway_instances"]
        )
        * out["module_specificity"]
        * (
            1
            + 0.15 * (out["module_axes"] - 1)
        )
    )

    out["passes_driver_filter"] = (
        (
            out["module_pathway_instances"]
            >= MIN_DRIVER_RECURRENCE
        )
        & (
            out["module_specificity"]
            >= MIN_DRIVER_SPECIFICITY
        )
    )

    return out.sort_values(
        [
            "module",
            "passes_driver_filter",
            "driver_score",
            "module_unique_pathways",
        ],
        ascending=[
            True,
            False,
            False,
            False,
        ],
    )


# =============================================================================
# REPRESENTATIVE PATHWAY TABLE
# =============================================================================

def make_module_representative_pathways(
    assignments: pd.DataFrame,
) -> pd.DataFrame:

    keep = assignments[
        assignments["assigned"]
    ].copy()

    columns = [
        "module",
        "library",
        "pathway",
        "direction",
        "cluster_size",
        "n_significant_phenotypes",
        "n_significant_axes",
        "significant_axes",
        "mean_NES_cognition",
        "mean_NES_amyloid",
        "mean_NES_tau",
        "mean_abs_NES",
    ]

    available = [
        c
        for c in columns
        if c in keep.columns
    ]

    return keep[
        available
    ].sort_values(
        [
            "module",
            "n_significant_phenotypes",
            "mean_abs_NES",
        ],
        ascending=[
            True,
            False,
            False,
        ],
    )


# =============================================================================
# FIGURES
# =============================================================================

def ordered_modules(
    module_summary: pd.DataFrame,
) -> list[str]:
    # Put shared modules first, then enhanced, then mixed.
    rank_map = {
        "Shared core": 0,
        "Amyloid-enhanced shared": 1,
        "Tau-enhanced shared": 2,
        "Cognition-enhanced shared": 3,
        "Amyloid-specific": 4,
        "Tau-specific": 5,
        "Cognition-specific": 6,
        "Mixed / context-dependent": 7,
        "Incomplete": 8,
    }

    temp = module_summary.copy()
    temp["_rank"] = temp["module_class"].map(
        rank_map
    ).fillna(99)

    return (
        temp.sort_values(
            [
                "_rank",
                "overall_mean_abs_NES",
            ],
            ascending=[
                True,
                False,
            ],
        )["module"]
        .tolist()
    )


def make_module_heatmap(
    profiles: pd.DataFrame,
    module_summary: pd.DataFrame,
    outdir: Path,
):
    modules = ordered_modules(
        module_summary
    )

    pivot = profiles.pivot_table(
        index="module",
        columns="phenotype",
        values="median_NES",
        aggfunc="first",
    ).reindex(
        index=modules,
        columns=PHENOTYPES,
    )

    sig = profiles.pivot_table(
        index="module",
        columns="phenotype",
        values="significant_fraction",
        aggfunc="first",
    ).reindex(
        index=modules,
        columns=PHENOTYPES,
    )

    fig_h = max(
        4.2,
        0.31 * len(modules) + 1.8,
    )

    fig, ax = plt.subplots(
        figsize=(7.2, fig_h)
    )

    vmax = max(
        1.0,
        float(
            np.nanmax(
                np.abs(
                    pivot.to_numpy()
                )
            )
        ),
    )

    im = ax.imshow(
        pivot.to_numpy(),
        cmap="coolwarm",
        vmin=-vmax,
        vmax=vmax,
        aspect="auto",
        interpolation="nearest",
    )

    ax.set_xticks(
        np.arange(len(PHENOTYPES))
    )

    ax.set_xticklabels(
        [
            PHENOTYPE_LABELS[p]
            for p in PHENOTYPES
        ],
        rotation=42,
        ha="right",
    )

    ax.set_yticks(
        np.arange(len(modules))
    )

    ax.set_yticklabels(
        modules,
        fontsize=5.5,
    )

    # Dot means a majority of representative pathways are significant for
    # that phenotype.
    for i in range(len(modules)):
        for j in range(len(PHENOTYPES)):
            value = sig.iloc[i, j]

            if (
                pd.notna(value)
                and value >= MODULE_SIG_FRACTION_FOR_DOT
            ):
                ax.text(
                    j,
                    i,
                    "•",
                    ha="center",
                    va="center",
                    fontsize=7.0,
                    color="black",
                )

    # Axis separators.
    ax.axvline(
        2.5,
        linewidth=0.8,
    )
    ax.axvline(
        5.5,
        linewidth=0.8,
    )

    ax.set_title(
        "Weighted AREA biological modules across phenotypes",
        fontsize=9.2,
        fontweight="bold",
        pad=11,
    )

    ax.text(
        0.5,
        1.015,
        (
            "Cell = median NES across nonredundant representative pathways; "
            "dot = ≥50% of module representatives significant"
        ),
        transform=ax.transAxes,
        ha="center",
        fontsize=5.2,
        color=MUTED,
    )

    cbar = fig.colorbar(
        im,
        ax=ax,
        fraction=0.028,
        pad=0.025,
    )

    cbar.set_label(
        "Median NES",
        fontsize=5.7,
    )

    cbar.ax.tick_params(
        labelsize=5.0,
    )

    fig.subplots_adjust(
        left=0.25,
        right=0.93,
        top=0.89,
        bottom=0.20,
    )

    fig.savefig(
        outdir / "refined_module_phenotype_heatmap.png",
        dpi=600,
        bbox_inches="tight",
    )

    fig.savefig(
        outdir / "refined_module_phenotype_heatmap.pdf",
        bbox_inches="tight",
    )

    plt.close(fig)


def make_axis_profile_figure(
    axis_profiles: pd.DataFrame,
    module_summary: pd.DataFrame,
    outdir: Path,
):
    modules = ordered_modules(
        module_summary
    )

    pivot = axis_profiles.pivot_table(
        index="module",
        columns="axis",
        values="mean_axis_NES",
        aggfunc="first",
    ).reindex(
        index=modules,
        columns=AXES,
    )

    fig_h = max(
        4.2,
        0.30 * len(modules) + 1.6,
    )

    fig, ax = plt.subplots(
        figsize=(6.5, fig_h)
    )

    y = np.arange(len(modules))
    width = 0.22

    for k, axis in enumerate(AXES):
        ax.barh(
            y + (k - 1) * width,
            pivot[axis],
            height=width,
            label=axis,
        )

    ax.axvline(
        0,
        linewidth=0.8,
    )

    ax.set_yticks(y)
    ax.set_yticklabels(
        modules,
        fontsize=5.4,
    )

    ax.invert_yaxis()

    ax.set_xlabel(
        "Mean module NES"
    )

    ax.set_title(
        "Relative module strength across cognition, amyloid, and tau",
        fontsize=8.8,
        fontweight="bold",
    )

    ax.legend(
        frameon=False,
        ncol=3,
        loc="upper center",
        bbox_to_anchor=(0.5, 1.01),
    )

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    ax.grid(
        axis="x",
        alpha=0.15,
    )

    fig.tight_layout()

    fig.savefig(
        outdir / "refined_module_axis_profiles.png",
        dpi=600,
        bbox_inches="tight",
    )

    fig.savefig(
        outdir / "refined_module_axis_profiles.pdf",
        bbox_inches="tight",
    )

    plt.close(fig)


def make_driver_gene_figure(
    drivers: pd.DataFrame,
    module_summary: pd.DataFrame,
    outdir: Path,
    top_per_module: int,
):
    if len(drivers) == 0:
        return

    modules = ordered_modules(
        module_summary
    )

    rows = []

    for module in modules:
        sub = drivers[
            (
                drivers["module"] == module
            )
            & (
                drivers["passes_driver_filter"]
            )
        ].head(
            top_per_module
        )

        for _, row in sub.iterrows():
            rows.append(
                {
                    "module": module,
                    "gene": row["gene"],
                    "driver_score": row["driver_score"],
                    "specificity": row["module_specificity"],
                    "recurrence": row["module_pathway_instances"],
                }
            )

    if not rows:
        return

    plot_df = pd.DataFrame(rows)

    # Build a compact module/gene y label.
    plot_df["label"] = (
        plot_df["module"]
        + " | "
        + plot_df["gene"]
    )

    plot_df = plot_df.iloc[::-1]

    fig_h = max(
        5.0,
        0.18 * len(plot_df) + 1.5,
    )

    fig, ax = plt.subplots(
        figsize=(7.0, fig_h)
    )

    ax.barh(
        plot_df["label"],
        plot_df["driver_score"],
    )

    ax.set_xlabel(
        "Module-specific driver score"
    )

    ax.set_title(
        "Top module-specific leading-edge genes",
        fontsize=8.8,
        fontweight="bold",
    )

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    ax.grid(
        axis="x",
        alpha=0.15,
    )

    ax.tick_params(
        axis="y",
        labelsize=4.8,
    )

    fig.tight_layout()

    fig.savefig(
        outdir / "refined_module_driver_genes.png",
        dpi=600,
        bbox_inches="tight",
    )

    fig.savefig(
        outdir / "refined_module_driver_genes.pdf",
        bbox_inches="tight",
    )

    plt.close(fig)


# =============================================================================
# MAIN
# =============================================================================

def main():
    args = parse_args()

    root = Path(args.biology_root)
    outdir = Path(args.outdir)

    outdir.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 100)
    print("REFINED WEIGHTED AREA BIOLOGICAL MODULE ANALYSIS")
    print("=" * 100)
    print()

    long_df, reps, clusters = load_inputs(
        root
    )

    rules = make_rule_table()

    rules.to_csv(
        outdir / "module_rules.csv",
        index=False,
    )

    assignments = assign_representatives(
        reps
    )

    assignments.to_csv(
        outdir / "module_assignment_audit.csv",
        index=False,
    )

    assigned = assignments[
        assignments["assigned"]
    ]

    unassigned = assignments[
        ~assignments["assigned"]
    ]

    unassigned.to_csv(
        outdir / "unassigned_representative_pathways.csv",
        index=False,
    )

    rep_long = representative_long(
        long_df,
        assignments,
    )

    profiles = make_module_phenotype_profiles(
        rep_long
    )

    profiles.to_csv(
        outdir / "module_phenotype_profiles.csv",
        index=False,
    )

    axis_profiles = make_module_axis_profiles(
        profiles
    )

    axis_profiles.to_csv(
        outdir / "module_axis_profiles.csv",
        index=False,
    )

    summary = make_module_summary(
        assignments,
        profiles,
        axis_profiles,
    )

    summary.to_csv(
        outdir / "module_summary.csv",
        index=False,
    )

    drivers = make_driver_genes(
        rep_long
    )

    drivers.to_csv(
        outdir / "module_driver_genes.csv",
        index=False,
    )

    rep_table = make_module_representative_pathways(
        assignments
    )

    rep_table.to_csv(
        outdir / "module_representative_pathways.csv",
        index=False,
    )

    make_module_heatmap(
        profiles,
        summary,
        outdir,
    )

    make_axis_profile_figure(
        axis_profiles,
        summary,
        outdir,
    )

    make_driver_gene_figure(
        drivers,
        summary,
        outdir,
        args.top_drivers_per_module,
    )

    # -------------------------------------------------------------------------
    # Console summary
    # -------------------------------------------------------------------------
    n_total = reps[
        ["library", "pathway"]
    ].drop_duplicates().shape[0]

    n_assigned = assigned[
        ["library", "pathway"]
    ].drop_duplicates().shape[0]

    print(
        f"Representative pathways: {n_total:,}"
    )
    print(
        f"Assigned to biological modules: {n_assigned:,} "
        f"({100 * n_assigned / n_total:.1f}%)"
    )
    print(
        f"Unassigned: {n_total - n_assigned:,}"
    )
    print()

    print("MODULE SUMMARY")
    print()

    show_cols = [
        "module",
        "module_class",
        "n_representative_pathways",
        "cognition_mean_NES",
        "amyloid_mean_NES",
        "tau_mean_NES",
        "enhancement_delta",
    ]

    print(
        summary[
            show_cols
        ].to_string(
            index=False
        )
    )

    print()
    print("TOP MODULE-SPECIFIC DRIVER GENES")
    print()

    if len(drivers) > 0:
        for module in ordered_modules(
            summary
        ):
            top = drivers[
                (
                    drivers["module"] == module
                )
                & (
                    drivers["passes_driver_filter"]
                )
            ].head(
                args.top_drivers_per_module
            )

            if len(top) == 0:
                continue

            genes = ", ".join(
                top["gene"].tolist()
            )

            print(
                f"{module}: {genes}"
            )

    print()
    print("=" * 100)
    print("DONE")
    print("=" * 100)
    print()
    print(f"Outputs: {outdir}")


if __name__ == "__main__":
    main()
